CREATE TABLE IF NOT EXISTS chats (
	id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
  room_id VARCHAR (191) UNIQUE
);

CREATE TABLE IF NOT EXISTS participants (
	id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
  chat_id INTEGER NOT NULL,
  user_id INTEGER NOT NULL,
  FOREIGN KEY (chat_id) REFERENCES chats(id)
);

CREATE TABLE IF NOT EXISTS messages (
	id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
    
  chat_id INTEGER NOT NULL,
  FOREIGN KEY (chat_id) REFERENCES chats(id),
    
  sender_id INTEGER NOT NULL,
  text TEXT NOT NULL,
  sent_time DATETIME DEFAULT CURRENT_TIMESTAMP
);